# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-11 16:46
from __future__ import unicode_literals

import blog.models.image
from django.db import migrations, models
import django.db.models.deletion
import essy.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, storage=essy.storage.GoogleCloudStorage(), upload_to=blog.models.image.format_storage_path)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.Entry')),
            ],
            options={
                'ordering': ('-thumbnail',),
            },
        ),
    ]
