# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-12 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='EntryImage',
        ),
    ]
