# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import essy.storage
import home.models.blog.post


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170702_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(storage=essy.storage.GoogleCloudStorage(), upload_to=home.models.blog.post.format_storage_path)),
                ('thumbnail', models.ImageField(storage=essy.storage.GoogleCloudStorage(), upload_to=home.models.blog.post.format_storage_path)),
                ('body', models.TextField()),
                ('github', models.URLField(default='https://github.com/scottc11', max_length=250)),
            ],
        ),
    ]
