# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-15 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import essy.storage
import home.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='https://github.com/scottc11', max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default='', storage=essy.storage.GoogleCloudStorage(), upload_to=home.models.project.format_storage_path),
        ),
    ]
