# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import essy.storage
import home.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170917_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, storage=essy.storage.GoogleCloudStorage(), upload_to=home.models.post.format_storage_path),
        ),
    ]
