# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170923_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('icon_class', models.CharField(max_length=30)),
                ('link', models.URLField(blank=True, max_length=250)),
            ],
        ),
    ]
