# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_socialmediaaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='media_accounts',
            field=models.ManyToManyField(to='home.SocialMediaAccount'),
        ),
    ]
