# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import essy.storage
import home.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_project_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schematic',
            field=models.ImageField(blank=True, storage=essy.storage.GoogleCloudStorage(), upload_to=home.models.post.format_storage_path),
        ),
    ]
