# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180623_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-order_weight',)},
        ),
        migrations.AddField(
            model_name='project',
            name='order_weight',
            field=models.IntegerField(choices=[(1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=1),
        ),
    ]
