# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180623_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
