# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_project_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
