# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-02 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180624_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_goal',
        ),
        migrations.RemoveField(
            model_name='project',
            name='idea',
        ),
    ]
